collections:
  projects:
    output: true
    permalink: /projects/:name/
  
baseurl:
exclude: ['CNAME', 'README.md']

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "projects"
    values:
      layout: "collection-item"
      invert-colors: false
      transparent-text: true
